data:
  root: /home/a123456/SEA-/MMFi
  seq_len: 20
  cache_dir: /home/a123456/SEA-/MMFi_cache

train:
  batch_size: 16
  epochs: 50
  lr: 0.0001

model:
  dim: 256
  num_joints: 17

domain:
  source: [E01, E02, E03]
  target: [E04]

log:
  save_dir: ./outputs
  print_freq: 20